### ISSUE TITLE
HTML report _and_ log output?

### ISSUE THREAD

**Issue by nomeata** [feuerbach/tasty-html#20]
It seems that by default, passing `--html report.html` will completely quiet the standard output. I think it might be nice, in some circumstances, to have both. Is that easily possible?

**Comment by feuerbach** [comment]
I think composeReporters is what you want: https://hackage.haskell.org/package/tasty-1.2.3/docs/Test-Tasty-Ingredients.html#v:composeReporters

**Comment by nomeata** [comment]
Thanks, indeed! I had to look up the definition of `defaultIngredients` and break it up though.

Maybe a pointer to that function in the documentation of https://hackage.haskell.org/package/tasty-html-0.4.1.1/docs/Test-Tasty-Runners-Html.html might be helpful? Otherwise, feel free to close this.

**Comment by feuerbach** [comment]
Agree — if you have a chance to add a link or even a small example to the haddocks, please do.
